\documentclass[12pt,reqno,final]{amsart}
\usepackage[round,numbers,sort&compress]{natbib}
\usepackage{graphicx}
\usepackage{times}
\usepackage{rotating}
\usepackage{subfig}

\title[]{}

\setlength{\textwidth}{6.25in}
\setlength{\textheight}{8.75in}
\setlength{\evensidemargin}{0in}
\setlength{\oddsidemargin}{0in}
\setlength{\topmargin}{-.35in}
\setlength{\parskip}{.1in}
\setlength{\parindent}{0.0in}

\theoremstyle{plain}
\newtheorem{thm}{Theorem}
\newtheorem{corol}[thm]{Corollary}
\newtheorem{prop}[thm]{Proposition}
\newtheorem{lemma}[thm]{Lemma}
\newtheorem{defn}[thm]{Definition}
\newtheorem{hyp}[thm]{Hypothesis}
\newtheorem{example}[thm]{Example}
\newtheorem{conj}[thm]{Conjecture}
\newtheorem{algorithm}[thm]{Algorithm}
\newtheorem{remark}{Remark}
\renewcommand\thethm{\arabic{thm}}
\renewcommand{\theremark}{}

\numberwithin{equation}{part}
\renewcommand\theequation{\arabic{equation}}
\renewcommand\thesection{\arabic{section}}
\renewcommand\thesubsection{\thesection.\arabic{subsection}}
\renewcommand\thefigure{\arabic{figure}}
\renewcommand\thetable{\arabic{table}}
\renewcommand\thefootnote{\arabic{footnote}}

\begin{document}
<<echo=FALSE>>=
## Load some necessary packages silently
library(magrittr)
@

In this document, I will try to fully describe, in a single place, all of the known differences between \texttt{ouch} and \texttt{OUwie}, focusing especially on differences in how they compute the weight and covariance matrices, as those are key to the fitting procedures of each program.
To pick a particular case, I will use the sample data contained in the 'tworegime' dataset that is part of \texttt{OUwie}.
<<echo=T>>=
library(OUwie)
data(tworegime)
ls()

@

Some cursory examination of this dataset makes it clear it is a realistic phylogeny with 64 tips and 63 internal nodes (no polytomies), with a single regime switch occurring between the ancestral black regime and the red regime.

<<echo=F, fig.cap="The 'tworegime' phylogeny and regime painting." fig.height=6, fig.width=3, units='in', res=300>>=
plot(tree)
nodelabels(pch=21, bg=tree$node.label)
@

An examination of the phenotypic data suggests that the species in the different regimes have different mean phenotypic values.
<<echo=F, fig.cap="Phenotypic data for the two regimes." fig.height=3, fig.width=3, units='in', res=300>>=
with(trait, plot(as.factor(Reg), X, xlab='Regime', ylab="Trait"))

@

I will fit this tree and phenotypic data to an Ornstein-Uhlenbeck model with a single value for $\alpha$ and $\sigma$ and separate optima for the two regimes using 'model="OUM"' in a call to the function OUwie() in the \texttt{OUwie} package.
Note that I am specifiying the options 'scaleHeight=TRUE' and 'root.station=TRUE' to make the fitting procedure as close to the one used by \texttt{ouch} as possible, as \texttt{ouch} scales the tree height to be equal to 1 and does not estimate the root state $\theta_0$ but instead draws it from the stationary distribution of the OU process.
This produces estimates of $\alpha=1.39$, $\sigma^2=0.65$, $\theta_1=1.68$, and $\theta_2=0.81$.
<<echo=T>>=
OUwie(tree, trait, model="OUM", scaleHeight=TRUE, root.station=TRUE, quiet=TRUE)

@

\end{document}